### ISSUE TITLE
Rollup failed to resolve import

### ISSUE THREAD

**Issue by mkonars** [jasonsturges/vite-typescript-npm-package#2]
Hi, it seems like rollup cannot resolve any files inside nested folders.

I have added new file inside _src/components/component.ts_

```
export class Component {
  public move() {}
}
```

and I want to export it to the bundle. I added this to _index.ts_

```
// Main library exports - these are packaged in your distributable
export const isOdd = (n: number): boolean => {
  return !!(n & 1);
};

export * from "components/component";
```
 

_error during build:
Error: [vite]: Rollup failed to resolve import "components/component" from "C:/tmp/trash/npm_test/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`_

Could you help?

**Comment by mkonars** [comment]
Don't know if this is the way to go, but I have managed to fix this issue, by aliasing _src_ folder as described here [https://stackoverflow.com/questions/68241263/absolute-path-not-working-in-vite-project-react-ts?rq=2](url)

vite.config.ts:
```
export default defineConfig({
  base: "./",
  plugins: [dts({ rollupTypes: true }), react()],
  resolve: {
    alias: {
      src: path.resolve("src/"),
    },
  },
```
tsconfig.ts:
```
  "compilerOptions": {
    "baseUrl": "./",
    "rootDir": "./",

```
and then all the imports/exports in the solution must be updated to begin with _src_

**Comment by jasonsturges** [comment]
Few things in play...

These glob patterns can be finicky depending on your version of Node.  What version are you running?

Your export appears wrong, check your casing and path:
src/index.ts:
```ts
export * from "components/component"; // <!-- lowercase does not match the `Component` export
```

...should be:
```ts
export * from "./components/Component"
```

...which builds as:

<img width="1138" alt="image" src="https://github.com/jasonsturges/vite-typescript-npm-package/assets/1213591/14c084bc-30ad-485c-a173-0855222e113f">

The way I normally build my libraries is to rollup all my components to the top level index.

Every component I want built into the library is explicitly declared in the top-level index.ts:

src/index.ts:
```ts
// Main library exports - these are packaged in your distributable
export { Component } from "./components/Component"
```

<img width="1045" alt="image" src="https://github.com/jasonsturges/vite-typescript-npm-package/assets/1213591/7c059b2d-9b50-40ee-aed8-a5a83300f619">

These can be rolled up in different ways; for example: you could have a `components/index.ts` that includes all components which is re-exported from the top-level as `export * from "./components";`

Going down the TSConfig routes adds some complexity, but your root and base directories are:

tsconfig.json:
```json
    "baseUrl": "./src",
    "rootDir": "./src",
```

...which is not needed if you follow the examples above.

All of this depends on how you want to develop, refactor, isolate, tree shake, and ultimately use the library in your application projects.  

Let me know if you are still facing issues.

**Comment by mkonars** [comment]
Hi, thanks for reply.
Changing import to be relative from `export * from "components/component";` to `export * from "./components/Component";` indeed helped. The casing was ok, cause the file name was lowercase, but I have changed that now just in case.

However, if this _Component_ is referencing another component in different folder, then the problem is back.

I have added _src/lib/LibComponent.ts_

![image](https://github.com/jasonsturges/vite-typescript-npm-package/assets/20971484/e36556c9-3213-45b4-a78c-e3edfee5ec6a)

and _src/lib/index.ts_
![image](https://github.com/jasonsturges/vite-typescript-npm-package/assets/20971484/44d6c7ce-98ab-4050-be62-5c6b2c4ca2f2)


and I am referencing it inside src/components/Component.ts

![image](https://github.com/jasonsturges/vite-typescript-npm-package/assets/20971484/6ca9ab98-298e-4a37-b452-65242ceb0730)


Now, if I have absolute import `import { LibComponent } from "lib";`, I get the same error as before.
When I change it to relative import  `import { LibComponent } from "../lib";` it works fine, but I would like to avoid changing all the auto imports.

I have just upgraded to the node _v18.18.0_ and it's the same result.

**Comment by jasonsturges** [comment]
Does your IDE not resolve your imports for you?

Are you trying to do module / project level `@` style imports?

Unless you configure Vite and TypeScript, these are just regular imports like you'd find in any project.

In the simpliest form:

<img width="1138" alt="image" src="https://github.com/jasonsturges/vite-typescript-npm-package/assets/1213591/397e1e10-6ab0-47de-b2ab-1c5a9c35324d">


Or, if you want to use indexes to re-export folders:

<img width="1138" alt="image" src="https://github.com/jasonsturges/vite-typescript-npm-package/assets/1213591/2049251d-494d-4a42-a5cf-81cf99d6a12f">

**Comment by mkonars** [comment]
I'm using Visual Studio Code and I just want it to resolve the imports using relative paths like `../lib`. It seems that it does it only if I remove _baseUrl_ from _tsconfig.ts_. Strange that it works for you.

Anyway, don't want to trouble you any longer. I understand it's probably some issue with tsconfig or VS. Thanks for help.

**Comment by jasonsturges** [comment]
VSCode -> Settings -> TypeScript Import Module Specifier

![c1](https://github.com/jasonsturges/vite-typescript-npm-package/assets/1213591/d61aafd9-afe2-45ec-9d9f-8263fb5c6e35)

**Comment by mkonars** [comment]
Oh man, that did the trick :-) Thanks a lot.

**Comment by jasonsturges** [comment]
Other options, but excellent.  Some time I'll explore module-level `@` import specifiers.
